[theme]
primaryColor = "#eca413"
backgroundColor = "#fdfcf8"
secondaryBackgroundColor = "#fcfaf8"
textColor = "#1b170d"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
